spring:
  profiles:
    active: druid
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 30
        min-idle: 10
        max-wait: -1
    timeout: 10000000


server:
  port: 5000
logging:
  level:
    com.cattle.mapper: debug
